# This workflow will install Python dependencies, build a static site and publish to CloudFlare pages

name: Build stagic site

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.8.2
      - name: Configure Poetry
        run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local
      - name: Configure project dependencies cache
        uses: actions/cache@v3
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}
      - name: Install project dependencies
        run: poetry install
      - name: Build site
        run: poetry run python scripts/freeze_site.py
      - name: Upload build artefacts
        uses: actions/upload-artifact@v4.4.0
        with:
          name: site_build
          path: build/
          if-no-files-found: error

  deploy:
      runs-on: ubuntu-latest
      needs: [build]
      if: github.ref == 'refs/heads/main'
      env:
        CF_PROJ_NAME: 'lancefennell'
      steps:
        - name: Download build artefacts
          uses: actions/download-artifact@v4.1.8
        - name: Deploy site
          uses: cloudflare/wrangler-action@v3
          with:
            command: pages deploy build/ --project-name=$CF_PROJ_NAME
          env:
            CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
            CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
