# This workflow will install Python dependencies, build a static site and publish to CloudFlare pages

name: Build stagic site

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          version: "0.4.14"
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - name: Install project dependencies
        run: uv sync --dev
      - name: Build site
        run: uv run python scripts/freeze_site.py
      - name: Upload build artefacts
        uses: actions/upload-artifact@v4.4.0
        with:
          name: site_build
          path: build/
          if-no-files-found: error

  deploy:
      runs-on: ubuntu-latest
      needs: [build]
      env:
        CF_PROJ_NAME: 'lancefennell'
      steps:
        - name: Download build artefacts
          uses: actions/download-artifact@v4.1.8
        - name: Deploy site
          uses: cloudflare/wrangler-action@v3
          with:
            apiToken: ${{ secrets.CF_API_TOKEN }}
            accountId: ${{ secrets.CF_ACCOUNT_ID }}
            command: pages deploy build/ --project-name=$CF_PROJ_NAME
